version: "3.7"

services:
  rabbitmq:
    image: 'rabbitmq:3.8.0-management'
    restart: 'unless-stopped'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=test